# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 09:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='discount',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='serial_number', to='discounts.Discount'
            ),
        ),
    ]
